# Project Information
site_name: 超理图书馆
site_description: 本项目提供各超理书籍供各位超理爱好者学习
site_author: 超理团队
site_url: http://b.hcl10.ml/
strict: true

# Repository
repo_name: 'HCl-10/chaoli-books'
repo_url: 'https://github.com/HCl-10/chaoli-books'
edit_uri: 'http://b.hcl10.ml/edit-landing/?ref='

# Copyright
copyright: 'Copyright &copy; 2008 - 2021 Chaoli Team'

# Contents
nav:
  - 简介:
    - 关于超理: index.md
    - Markdown 使用说明: friendly/exmp.md
  - 超理教材 九年级全一册:
    - 关于本书: cljc9/index.md
    - 绪言: cljc9/0.md
    - 第一单元 走进超理世界: cljc9/1.md
    - 第二单元 我们周围的空气: cljc9/2.md
    - 第三单元 氢: cljc9/3.md
    - 第四单元 锑能守恒定律: cljc9/4.md
    - 第五单元 锑与锑场: cljc9/5.md
    - 第六单元 赵明毅大师及其发现: cljc9/6.md
    - 第七单元 学习伟大的超理学家: cljc9/7.md
    - 第八单元 实验: cljc9/8.md
    - 第九单元 超理思想的传播与交流: cljc9/9.md
    - 结束语: cljc9/10.md
    - 附录: cljc9/11.md
    - 真·结语: cljc9/12.md
  - 大锑星百科全书:
    - mp3 杂化: bkqs/mp3zh.md
    - 发功: bkqs/fg.md
    - 高烷: bkqs/gw.md
    - 黑光: bkqs/hg.md
    - 聚甲烷: bkqs/jjw.md
    - 昆奶牛: bkqs/knn.md
    - 颅海龟: bkqs/lhg.md
    - 魔键: bkqs/mj.md
    - 氢合甲烷: bkqs/qhjw.md
    - 锑场: bkqs/tc.md
    - 锑星大学: bkqs/txdx.md
    - 赵明毅: bkqs/zmy.md
  - 雷论:
    - 总集: ralun/index.md
    - 运动力学讲解: ralun/ydlx.md
  - 丙酮著作集:
    - 关于普通高中学生邋遢现象的研究: acetone/lxtl.md
    - 喜阴的颅海龟和高原的昆奶牛: acetone/lhgknn.md
  - 超文:
    - Acid Hard (上): cw/Acid_Hard-A.md

# Theme
theme:
  name: null
  custom_dir: 'mkdocs-material/material'
  static_templates:
    - 404.html
  language: 'zh'
  palette:
    primary: 'white'
    accent: 'red'
  include_search_page: false
  search_index_only: true
  favicon: 'Antimoney.ico'
  icon:
    repo: fontawesome/brands/github
  feature:
    tabs: true
  font:
    text: 'Open Sans'
    code: 'Cascadia Mono'

# Customization
extra:
  search:
    language: 'jp'
  disqus: 'chaoli-books'
  pagetime: 'on'
  manifest: 'manifest.webmanifest'
  githash: ''
extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.1/highlight.min.js'
  - '_static/js/extra.js?v=16'
extra_css:
  - '_static/css/extra.css?v=13'
  - 'https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/katex.min.css'
  - 'https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.1/styles/default.min.css'

# Extensions
markdown_extensions:
  - admonition
  - attr_list
  - codehilite:
      guess_lang: false
      linenums: false
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.highlight:
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.progressbar
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
