# Project Information
site_name: 超理图书馆
site_description: 本项目提供各超理书籍供各位超理爱好者学习
site_author: 超理团队
site_url: http://b.hcl10.ml/
strict: true

# Repository
repo_name: 'HCl-10/chaoli-books'
repo_url: 'https://github.com/HCl-10/chaoli-books'
edit_uri: 'http://b.hcl10.ml/edit-landing/?ref='

# Copyright
copyright: 'Copyright &copy; 2008 - 2021 Chaoli Team'

# Contents
nav:
  - 简介:
    - 关于超理: index.md
  - 超理教材 九年级全一册:
    - 绪言: cljc9/0.md
    - 第一单元 走进超理世界: cljc9/1.md
    - 第二单元 我们周围的空气: cljc9/2.md
    - 第三单元 氢: cljc9/3.md
    - 第四单元 锑能守恒定律: cljc9/4.md
    - 第五单元 锑与锑场: cljc9/5.md
    - 第六单元 赵明毅大师及其发现: cljc9/6.md
    - 第七单元 学习伟大的超理学家: cljc9/7.md
    - 第八单元 实验: cljc9/8.md

# Theme
theme:
  name: null
  custom_dir: 'mkdocs-material/material'
  static_templates:
    - 404.html
  language: 'zh'
  palette:
    primary: 'white'
    accent: 'red'
  include_search_page: false
  search_index_only: true
  favicon: 'Antimoney.ico'
  icon: 'Antimoney.png'
  feature:
    tabs: true
  font:
    text: 'Fira Sans'
    code: 'Fira Mono'

# Customization
extra:
  search:
    language: 'jp'
  disqus: 'chaoli-books'
  copyright: '<a href="https://creativecommons.org/licenses/by-sa/4.0/deed.zh">CC BY-SA 4.0</a>'
  pagetime: 'on'
  manifest: 'manifest.webmanifest'
  githash: ''
extra_javascript:
  - '_static/js/extra.js?v=16'
  # - 'https://cdn.bootcss.com/KaTeX/0.11.1/contrib/auto-render.min.js'
extra_css:
  - '_static/css/extra.css?v=13'
  - 'https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/katex.min.css'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.highlight:
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.progressbar
  - pymdownx.smartsymbols
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
